### ISSUE TITLE
refactor: set SLA for app configuration (SNYK-CC-AZURE-608) 

### ISSUE THREAD

**Issue by kov117** [equinor/terraform-azurerm-app-config#5]
SNYK-issue for the azurerm-app-config:

- An SLA should be used for App Configuration ([SNYK-CC-AZURE-540](https://snyk.io/security-rules/SNYK-CC-AZURE-608))

  - Severity: Medium

  - Issue:  An SLA should be used for App Configuration 

  - Impact:  Using the free SKU might negatively impact the availability of the App Configuration 

  - Resolve: Set `sku` to `standard`

  Ref:

- [https://azure.microsoft.com/en-gb/pricing/details/app-configuration/](url)

- [https://docs.microsoft.com/en-us/azure/templates/microsoft.appconfiguration/configurationstores?tabs=json](url)

**Comment by helenakallekleiv** [comment]
Issue permanently ignored in SNYK, resolved by setting default value to `standard` for `sku` variable.

Closing this.
