### ISSUE TITLE
refactor: set the diagnostic setting to captures appropriate categories (SNYK-CC-AZURE-552)

### ISSUE THREAD

**Issue by kov117** [equinor/terraform-azurerm-app-config#6]
SNYK-issue for the azurerm-event-grid:

- Ensure Diagnostic Setting captures appropriate categories ([SNYK-CC-AZURE-552](https://snyk.io/security-rules/SNYK-CC-AZURE-552))

  - Severity: Low

  - Issue: Ensure Diagnostic Setting captures appropriate categories

  - Impact:   Not capturing the diagnostic setting categories for appropriate management activities leads to missing important alerts  

  - Resolve: Set log blocks for the categories `Administrative`,`Alert`,`Policy`,`Security` with `enabled` set to `true` for each

  Ref:

- [https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting#category](url)

- [https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/resource-manager-diagnostic-settings](url)

- CIS Benchmark v1.3.1 - 5.1.2 Ensure Diagnostic Setting captures appropriate categories

**Comment by helenakallekleiv** [comment]
Closing this, ref. https://github.com/equinor/terraform-azurerm-app-config/issues/7#issuecomment-1516292605
